config/routes.rb
Rails.application.routes.draw do
   match "/stripe_checkout", :to => "subscriptions#stripe_checkout", :via => [:post]
  get "users/index"
  resources :static_pages
  resources :cards
  resources :cheatsheets
  devise_for :users
  resources :users, :only => [:show]
  match "/users/:id", to: "users#show", via: "get"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/cheatsheet.rb
# == Schema Information
#
# Table name: cheatsheets
#
#  id           :bigint           not null, primary key
#  display_name :string
#  description  :string
#  os           :string
#  image        :string
#  card_count   :integer
#  level        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  topic        :string
#

class Cheatsheet < ApplicationRecord
end

app/controllers/cheatsheets_controller.rb
class CheatsheetsController < ApplicationController
  before_action :set_cheatsheet, only: [:show, :edit, :update, :destroy]

  # GET /cheatsheets
  # GET /cheatsheets.json
  def index
    @cheatsheets = Cheatsheet.all
    if !current_user
      # puts "is a guest"
      @guest_id = SecureRandom.uuid
      @user_id = "nil"
      @red_count = 0
      @yellow_count = 0
      @green_count = 0
      @white_count = 6
      @class_results = "navbar-menu button"
      @points_this_week = "-*-"
      @points_tooltip_text = "As a User, your learning earns Points!"
    else
      # is a user
      # puts "is a user"
      # todo - check that the user was not just a guest and there are scorecards for them
      if current_user.trial_days? >= 3
        @is_purple = "is-success"
      elsif current_user.trial_days? == 2
        @is_purple = "is-warning"
      else
        @is_purple = "is-danger"
      end
      @guest_id = "nil"
      @user_id = current_user.id
      # Points this week btn
      if current_user
        @red_count = Scorecard.redcards.where(user_id: current_user.id).all.count
        @yellow_count = Scorecard.yellowcards.where(user_id: current_user.id).count
        @green_count = Scorecard.greencards.where(user_id: current_user.id).count
        @white_count = Scorecard.whitecards.where(user_id: current_user.id).count
        @points_this_week = DsPoint.where(user_id: current_user.id).points_this_week.to_a[0][1]
        @points_last_week = DsPoint.where(user_id: current_user.id).points_last_week.to_a[0][1]
        if @points_this_week > @points_last_week
          @class_results = "navbar-menu button is-primary tooltip is-tooltip-bottom"
          @points_tooltip_text = "You're ahead of last week's points of " + @points_last_week.to_s + "!"
        elsif @points_this_week < @points_last_week
          @class_results = "navbar-menu button is-danger tooltip is-tooltip-bottom"
          @points_tooltip_text = "You're under last week's total points of " + @points_last_week.to_s + "."
        else
          # they are tied
          @class_results = "navbar-menu button is-warning tooltip is-tooltip-bottom"
          @points_tooltip_text = "You've tied last week's total points of " + @points_last_week.to_s + "!"
        end
      else
        @class_results = "navbar-menu button tooltip is-tooltip-bottom"
        @points_this_week = "-*-"
      end
      # end Points this week btn
    end

  end

  # GET /cheatsheets/1
  # GET /cheatsheets/1.json
  def show
    @cards = Card.where(cheatsheet_id: @cheatsheet.id)
    @cheatsheets = Cheatsheet.all
          if current_user.trial_days? >= 3
        @is_purple = "is-success"
      elsif current_user.trial_days? == 2
        @is_purple = "is-warning"
      else
        @is_purple = "is-danger"
      end
      @guest_id = "nil"
      @user_id = current_user.id
      # Points this week btn
      if current_user
        @red_count = Scorecard.redcards.where(user_id: current_user.id).all.count
        @yellow_count = Scorecard.yellowcards.where(user_id: current_user.id).count
        @green_count = Scorecard.greencards.where(user_id: current_user.id).count
        @white_count = Scorecard.whitecards.where(user_id: current_user.id).count
        @points_this_week = DsPoint.where(user_id: current_user.id).points_this_week.to_a[0][1]
        @points_last_week = DsPoint.where(user_id: current_user.id).points_last_week.to_a[0][1]
        if @points_this_week > @points_last_week
          @class_results = "navbar-menu button is-primary tooltip is-tooltip-bottom"
          @points_tooltip_text = "You're ahead of last week's points of " + @points_last_week.to_s + "!"
        elsif @points_this_week < @points_last_week
          @class_results = "navbar-menu button is-danger tooltip is-tooltip-bottom"
          @points_tooltip_text = "You're under last week's total points of " + @points_last_week.to_s + "."
        else
          # they are tied
          @class_results = "navbar-menu button is-warning tooltip is-tooltip-bottom"
          @points_tooltip_text = "You've tied last week's total points of " + @points_last_week.to_s + "!"
        end
      else
        @class_results = "navbar-menu button tooltip is-tooltip-bottom"
        @points_this_week = "-*-"
      end
  end

  # GET /cheatsheets/new
  def new
    @cheatsheet = Cheatsheet.new
  end

  # GET /cheatsheets/1/edit
  def edit
  end

  # POST /cheatsheets
  # POST /cheatsheets.json
  def create
    @cheatsheet = Cheatsheet.new(cheatsheet_params)

    respond_to do |format|
      if @cheatsheet.save
        format.html { redirect_to @cheatsheet, notice: 'Cheatsheet was successfully created.' }
        format.json { render :show, status: :created, location: @cheatsheet }
      else
        format.html { render :new }
        format.json { render json: @cheatsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cheatsheets/1
  # PATCH/PUT /cheatsheets/1.json
  def update
    respond_to do |format|
      if @cheatsheet.update(cheatsheet_params)
        format.html { redirect_to @cheatsheet, notice: 'Cheatsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @cheatsheet }
      else
        format.html { render :edit }
        format.json { render json: @cheatsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheatsheets/1
  # DELETE /cheatsheets/1.json
  def destroy
    @cheatsheet.destroy
    respond_to do |format|
      format.html { redirect_to cheatsheets_url, notice: 'Cheatsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cheatsheet
      @cheatsheet = Cheatsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cheatsheet_params
      params.require(:cheatsheet).permit(:display_name, :description, :os, :image, :level )
    end
end

app/helpers/cheatsheets_helper.rb
module CheatsheetsHelper
end

app/views/cheatsheets/_form.html.erb
  <%= form_with(model: cheatsheet, local: true) do |form| %>
    <% if cheatsheet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(cheatsheet.errors.count, "error") %> prohibited this cheatsheet from being saved:</h2>

        <ul>
        <% cheatsheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :display_name, class:"label is-large has-text-white" %>
      <%= form.text_field :display_name, class:"control input is-success" %>
    </div>

    <div class="field">
      <%= form.label :description, class:"label is-large has-text-white" %>
      <%= form.text_field :description, class:"control input is-success" %>
    </div>

    <div class="field">
      <%= form.label :os, class:"label is-large has-text-white" %>
      <%= form.text_field :os, class:"control input is-success" %>
    </div>
    
    <div class="field">
      <%= form.label :image, class:"label is-large has-text-white" %>
      <%= form.text_field :image, class:"control input is-success" %>
    </div>
    
    <div class="field">
      <%= form.label :level, class:"label is-large has-text-white" %>
      <%= form.text_field :level, class:"control input is-success" %>
    </div>

    <div class="actions">
      <%= form.submit "create rec", class:"button is-large has-text-white is-success"%>
    </div>
  <% end %>

app/views/cheatsheets/edit.html.erb
<div class='container'>
  <div class='columns'>
    <div class='column'>
    
    <h1>Editing Cheatsheet</h1>

<%= render 'form', cheatsheet: @cheatsheet %>

<%= link_to 'Show', @cheatsheet %> |
<%= link_to 'Back', cheatsheets_path %>
    </div>
  </div>
</div>

app/views/cheatsheets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="columns">
  <div class='column mt-60'>

    <h1 class="title is-text-white mb-60">Cheatsheets</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Ostype</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @cheatsheets.each do |cheatsheet| %>
        <tr>
          <td><%= cheatsheet.display_name %></td>
          <td><%= cheatsheet.description %></td>
          <td><%= cheatsheet.os %></td>
          <td><%= link_to 'Show', cheatsheet %></td>
          <td><%= link_to 'Edit', edit_cheatsheet_path(cheatsheet) %></td>
          <td><%= link_to 'Destroy', cheatsheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Cheatsheet', new_cheatsheet_path %>
  </div>
</div>

app/views/cheatsheets/new.html.erb
<div class='container'>
  <div class='columns'>
    <div class='column'>
    
      <h1>New Cheatsheet</h1>

      <%= render 'form', cheatsheet: @cheatsheet %>

      <%= link_to 'Back', cheatsheets_path %>
    </div>
  </div>
</div>

app/views/cheatsheets/show.html.erb
<script>
  $(document).ready(function () {
    this_page = $(".vmargin-dss")
      .first()
      .data("page");

    $(".card").flip({ axis: 'y' });
    console.log("doc read cheatsheets");
    if (this_page == "cheatsheets") {
      // convert keycaps to actual keys
      $(".interface-1").each(function (i, val) {
        str = $(".interface-1").eq(i).text() + "";
        str = str.trim();
        // $("#interface-x").text(str);
        temp_var = str;
        keyarray = temp_var.split(", ");
        temp_var2 = "";
        $.each(keyarray, function (i, val) {
          temp_var2 = temp_var2 + ConvertKeyCaps(val);
        });
        $(".interface-1").eq(i).text("");
        $(".interface-1").eq(i).append(temp_var2);

        // IDE
        hljs.initHighlightingOnLoad();
        hljs.initHighlighting();
      });
    };
  });
</script>

<section class="section ls-features-cards">
  <div class='vmargin-dss hero-body container' data-page="<%= controller.controller_name %>">
    <div class='columns'>
      <div class=' column is-12 has-text-white'>
        <div class="flexcheat">
          <div class='image-area pt-20'>
            <figure class="image is-128x128">
              <img class="" src="<%=asset_path("sets/#{@cheatsheet.image}")%>" alt="Placeholder image">
            </figure>
          </div>
          <div class=''>
            <div class="has-text-white-bis is-size-3  pt-20">
              <%= @cheatsheet.display_name %>
            </div>
            <div class="has-text-white-bis is-size-3 ">
              <p class="is-size-4">
                <%= @cheatsheet.description %>
              </p>
            </div>
          </div>
          <div class=''>
            <p class="is-size-4  pt-20"> OS:
              <strong><%= @cheatsheet.os %></strong></p>
            <p class="is-size-4"> Level:
              <strong><%= @cheatsheet.level %></strong></p>
          </div>

        </div>
      </div>
    </div>
    <div class='column is-12 flexcheat'>
      <h6 class='is-5 small has-text-white-bis'>(Click a card to see the answer.)</h6>
    </div>
    <div class='column is-12 flexcheat'>

      <% @cards.each do |card| %>

      <div class="card">
        <div class="front">
          <header class="card-header has-background-dark has-text-white-bis">
            <p class="card-header-title has-text-white-bis">
              <%= card.question %>
            </p>

          </header>
          <div class="card-content">

            <div class="content front-content">
              <% if card.interface == 1 %>
              <div class="interface is-size-5 pl-20 pt-20 pb-20 testarea keyboard">
                <div class="testscale">
                  <div class='interface-1'>
                    <%= card.keycaps %>
                  </div>
                </div>
              </div>
              <% elsif card.interface == 2 %>
              <!-- terminal -->
              <pre><code class="shell">
<%= card.answer %>
              </code></pre>
              <% elsif card.interface == 3 %>
              <!-- IDE value must be flush left...-->
              <pre><code class="css">
<%= card.answer %>
                </code></pre>
              <% end  %>
            </div>
          </div>
        </div>
        <div class="back">
          <header class="card-header has-background-dark has-text-white-bis">
            <p class="card-header-title has-text-white-bis">
              <%= card.question %>
            </p>
          </header>
          <div class="card-content">
            <div class="content back-content">
              <% if card.description.length > 10 %>
              <div class='is-size-6 has-text-grey-dark is-uppercase pt-20'>Notes:</div>
              <div class='notes-area'>
                <%= card.description %>
              </div>
              <% end %>
              <% if !card.mnemonic.nil? %>
              <div class='is-size-6 has-text-grey-dark is-uppercase pt-20'>Mnemonic:</div>
              <div class='mnemonic-area'>
                <%= card.mnemonic %>
              </div>
              <% end %>
              <div class='citation-area pt-20'>
                <%= link_to card.citation_title, card.citation_url, target: "_blank", class: "is-size-7 hast_text-success is-capitalized is-italic" %>
              </div>
            </div>
          </div>
          </footer>
          <footer class="card-footer">


          </footer>
        </div>
      </div>

      <% end %>
    </div>


  </div>
  </div>
  </div>
</section>