config/routes.rb
Rails.application.routes.draw do
   match "/stripe_checkout", :to => "subscriptions#stripe_checkout", :via => [:post]
  get "users/index"
  resources :static_pages
  resources :cards
  resources :cheatsheets
  devise_for :users
  resources :users, :only => [:show]
  match "/users/:id", to: "users#show", via: "get"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/layouts/_footer.html.erb
<nav class='navbarBottom is-fixed-bottom'>
  <footer class="footer">
    <div class="container">
      <div class="columns has-text-centered-mobile">
        <div class="column is-4"><img class="ls-space" src="<%= image_path("blue-logo.png") %>"
            srcset="<%= image_path("blue-logo@2x.png") %> 320w, <%= image_path("blue-logo@3x.png") %> 400w, <%= image_path("blue-logo@3x.png") %> 1024w"
            title="LandSpeed BulmaStyle" width="197" height="45">

        </div>
        <div class="column is-2">
          <h5 class="title has-text-dark is-5">About</h5>
          <ul class="ls-footer-links">
            <li><a href="/">About</a></li>
            <li><a href="/">Templates</a></li>
            <li><a href="/">Integrations</a></li>
            <li><a href="/">servce</a></li>
            <li><a href="/">Feature</a></li>
            <li><a href="/">Testimonials</a></li>
          </ul>
        </div>
        <div class="column is-2">
          <h5 class="title has-text-dark is-5">Resources</h5>
          <ul class="ls-footer-links">
            <li><a href="/">Info</a></li>
            <li><a href="/">Tools</a></li>
            <li><a href="/">Podcasts</a></li>
            <li><a href="/">Ebooks</a></li>
            <li><a href="/">Tools</a></li>
            <li><a href="/">Videos</a></li>
          </ul>
        </div>
        <div class="column is-2">
          <h5 class="title has-text-dark is-5">Company</h5>
          <ul class="ls-footer-links">
            <li><a href="/">About Us</a></li>
            <li><a href="/">Support</a></li>
            <li><a href="/">Contact</a></li>
            <li><a href="/">Terms &amp; Conditions</a></li>
            <li><a href="/">FAQ</a></li>
            <li><a href="/">Press</a></li>
          </ul>
        </div>
      </div>
      <div class="columns ls-footer">
        <div class="column is-5 is-marginless has-text-centered-mobile content has-text-grey">
          <p>Copyright Crop 2017 &copy; Bulmasyle.com</p>
        </div>
        <div class="column is-7">
          <ul class="columns ls-bottom-links is-mobile is-multiline is-marginless">
            <li class="ls-bottom-link"><a href="/">Privacy Policy</a></li>
            <li class="ls-bottom-link"><a href="/">Customers</a></li>
            <li class="ls-bottom-link"><a href="/">Support</a></li>
            <li class="ls-bottom-link"><a href="/">New Features</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</nav>

app/views/layouts/_navigation.html.erb
<div class="hero-head">
  <nav class="navbar container ls-main-nav">
    <!-- Brand -->
    <div class="navbar-brand">
      <a href="#" class="navbar-item">
        <img src="<%= image_path("bulma-style.png") %>"
          srcset="<%= image_path("bulma-style@2x.png") %> 320w, <%= image_path("bulma-style@3x.png") %> 400w, <%= image_path("bulma-style@3x.png") %> 1024w"
          title="LandSpeed BulmaStyle" width="195">
      </a>
      <a role="button" class="navbar-burger has-text-info" data-target="mainNavMenu" aria-label="menu"
        aria-expanded="false"><span aria-hidden="true"></span><span aria-hidden="true"></span><span
          aria-hidden="true"></span>
      </a>
    </div>
    <!-- Navbar menu -->
    <div class="navbar-menu" id="mainNavMenu">
      <div class="navbar-end has-text-info">
        <% if user_signed_in? %>
        <a class="navbar-item has-text-info is-size-7 is-active" href="/">
          Review Today's Cards
        </a>
        <div class="navbar-item has-dropdown is-hoverable">
          <nav class="navbar" role="navigation" aria-label="dropdown navigation">
          </nav>
          <a class="navbar-link has-background-success has-text-info">Cheatsheets
          </a>
          <div class="navbar-dropdown has-background-success is-boxed">
            <% @cheatsheets.each do |cheatsheet| %>
            <%= link_to cheatsheet.display_name ,cheatsheet_path(cheatsheet.id), class:"navbar-item has-background-success has-text-info"%>
            <% end %>
          </div>
        </div>
        <%= link_to 'Sets', cheatsheets_path(), class:"navbar-item has-text-info" %>
        <a class="navbar-item has-text-info is-size-7" href="/">
          Metrics
        </a>
        <% else %>
        <%= link_to 'Why LearnShortcuts', root_path(), class:"navbar-item has-text-info is-active" %>
        <%= link_to 'Why it Works', "page_path('itworks')", class:"navbar-item has-text-info" %>
        <%= link_to 'Pricing', "subscriptions_path()", class:"navbar-item has-text-info" %>
        <a class="navbar-item " href="/">
          Blog
        </a>
        <%= link_to 'About', "static_pages_path()", class:"navbar-item has-text-info" %>
        <% end %>
      </div>
      <div class="navbar-end">
        <% if user_signed_in? %>
        <!-- User is signed in -->
        <% if current_user.must_pay? %>
        <div id="trial_button" class='navbar-item'>
          <%= link_to 'Days left in Trial:  ' + current_user.trial_days?.to_s, "subscriptions_path(", class:"navbar-item trial-flag button #{@is_purple} " %>
        </div>
        <% end %>
        <div class='navbar-item'>
          <button id="points-item" class="<%= @class_results %>">Points
            this week:
            <span id="nav-total-points" class="has-text-weight-bold ml-5">
              <%= @points_this_week%>
            </span>
          </button>
        </div>
        <% end %>
        <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <nav class="navbar" role="navigation" aria-label="dropdown navigation">
          </nav>
          <a class="navbar-link" href="/">
            <%= current_user.name  %>
          </a>
          <div class="navbar-dropdown is-boxed">
            <%= link_to 'Your Profile', user_path(current_user.id), class:"navbar-item" %>
            <hr class="navbar-divider">
            <a class="navbar-item" href="https://bulma.io/documentation/elements/box/">
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class =>"navbar-item" %>
          </div>
        </div>
        <div class="navbar-dropdown is-right">
          <a class="navbar-item">
            <div>
              <span class="icon is-small">
                <i class="fa fa-user-circle-o"></i>
              </span>
              Profile
            </div>
          </a>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class =>"navbar-item" %>
        </div>
        <% else %>
        <!-- Signup button for non-members -->
        <div class="navbar-item">
          <%= link_to "Log in", new_session_path(User), class:"button button-signup btn-outlined is-bold btn-align light-btn rounded raised" %>
          <%= link_to('Sign up', new_user_registration_path, :class =>"button button-signup btn-outlined is-bold btn-align light-btn rounded raised")  %>
        </div>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application+phone.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Required Meta Tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="icon" type="image/png" href=<%=image_path("favicon.png")%> />
  <title>Learnshortcuts</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138649824-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-138649824-1');
  </script>

</head>

<body>
  <%= yield %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Required Meta Tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="icon" type="image/png" href=<%=image_path("favicon.png")%> />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css" />
  <title>Learnshortcuts</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script>hljs.initHighlightingOnLoad();</script>

  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
  <script src="https://cdn.rawgit.com/nnattawat/flip/master/dist/jquery.flip.min.js"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138649824-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-138649824-1');
  </script>

</head>

<body class="site">
  <section class="hero ls-main-hero eheight">
    <%= render  "layouts/navigation" %>
    <main class="site-content">
      <%= yield %>
    </main>
  </section>
  <!-- /Hero and nav -->
  <%= render  "layouts/footer" %>
</body>

</html>